src/Entity/Property.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @UniqueEntity("title")
 * @Vich\Uploadable
 */
class Property
{

    const  HEAT  = [
        0  =>  ' électrique ' ,
        1  =>  ' gaz '
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $filename;
    /**
     * @var File|null
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, max=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     * @Assert\PositiveOrZero
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     * @Assert\PositiveOrZero
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     * @Assert\PositiveOrZero
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     * @Assert\PositiveOrZero
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     *
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean",options={"default":false})
     */
    private $sold;

    /**
     * @ORM\Column(type="datetime")
     */
    private $creted_at;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Option", inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;



    public function __construct()
    {
        $this->creted_at= new \DateTime();
        $this->sold=false;
        $this->options = new ArrayCollection();
    }

    public function getformatedprix():string {

        return number_format($this->price ,'0','  ','  ');
    }

    public function getSlug()
    {
        $slugify = new Slugify();
        return $slugify->slugify($this->title);
    }

    /*
     * cette function permet de returner les constant HEAT type de chaugade
     * si 1 aficher gaz si 0 afficher elcctier et le heat est une integer alors el permet de mettre dans
     * tableau self::
     */

    public function getHeatType():string {
        return self::HEAT[$this->heat];
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }


    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCretedAt(): ?\DateTimeInterface
    {
        return $this->creted_at;
    }

    public function setCretedAt(\DateTimeInterface $creted_at): self
    {
        $this->creted_at = $creted_at;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }
        return $this;
    }
    public function removeOption(Option $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeProperty($this);
        }
        return $this;
    }

    /**
     * @return string|null
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param string|null $filename
     */
    public function setFilename(?string $filename): void
    {
        $this->filename = $filename;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param null|File $imageFile
     */
    public function setImageFile(?File $imageFile): Property
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    /**
     * @return mixed
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * @param mixed $updated_at
     */
    public function setUpdatedAt($updated_at): void
    {
        $this->updated_at = $updated_at;
    }


}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\OptionsResolver\OptionsResolver;


class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface',IntegerType::class,['attr'=>['min'=>0]])
            ->add('rooms',IntegerType::class,['attr'=>['min'=>0]])
            ->add('bedrooms',IntegerType::class,['attr'=>['min'=>0]])
            ->add('floor',IntegerType::class,['attr'=>['min'=>0]])
            ->add('price',IntegerType::class,['attr'=>['min'=>0]])
            ->add('heat',ChoiceType::class,['choices'=>$this->getChoices()])
            ->add('options',EntityType::class,[
                'class'=>Option::class,
                'required'=>false,
                'choice_label'=>'name',
                'multiple'=>true
            ])
            ->add('imageFile',FileType::class,[
                'required'=>false
            ])
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('sold')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain'=>'forms'
        ]);
    }

    /*
      cette fn premrt de recuperee les type de chaufage et changer affichage avec chocsir le champ
    gaz ou elctricque avec une type choice type
     */
    private function getChoices()
    {
        $choices= Property::HEAT;
        $output=[];
        foreach ($choices as $k =>$v){
        $output[$v]=$k;
        }
        return $output;

    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Entity\PropertySearch;
use App\Form\ContactType;
use App\Form\PropertySearchType;
use App\Notification\ContactNotification;
use App\Repository\PropertyRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Property;

class PropertyController extends AbstractController
{
    /*
    injection de repo pour reduit le code et quand on'a pleuseur methode qui utilise le repository
    le mieux injectet et fait l'appele
     */

    /**
     * @var PropertyRepository
     */
    private $repository;
    /**
     * @var ObjectManager
     */
    private $em;

    public function __construct(PropertyRepository $repository, ObjectManager $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }

    /**
     * @Route("/property", name="property_index")
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */

    /*
     * autre methode de le mthre de le paramtre avecc autoohwring comme dans le demo
     * public function index(PropertyRepository $repository)
     */
    public function index(PaginatorInterface $paginator,Request $request)
    {
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);


        /*$property = new Property();
        $property->setTitle('Mon premier bien')
            ->setPrice('200000')
            ->setRooms(4)
            ->setBedrooms(3)
            ->setDescription('Une petite description')
            ->setSurface(60)
            ->setFloor(4)
            ->setHeat(1)
            ->setCity('Montpellier')
            ->setAddress('Avenue Gambetta')
            ->setPostalCode('34000');
        $em = $this->getDoctrine()->getManager();
        $em->persist($property);
        $em->flush(); */

        /* methode classic sans injection de reposottry et afficher les données et il ya autres methode
        dans projet demo
        $entityManager = $this->getDoctrine()->getManager();
        $property = $entityManager->getRepository(Property::class)->findAllVisble();
        */


        $property = $paginator->paginate(
            $this->repository->findAllVisbleQuery($search),
            $request->query->getInt('page', 1),
            12
        );

        return $this->render('property/index.html.twig', [
            'menu_courant' => 'properties',
            'properties'=>$property,
            'form'     => $form->createView()
        ]);
    }

    /**
     * @Route("/property/{slug}-{id}", name="property_show" , requirements={"slug": "[a-z0-9\-]*"})
     * @param Property $property
     * @param string $slug
     * @param Request $request
     * @param ContactNotification $notification
     * @return RedirectResponse|Response
     */
     public function show(Property $property,string $slug,Request $request, ContactNotification $notification)
     {

         /* quand on change dans url le slug el redrige auto dans le meme pages et il est tres important pour
         le refrancment */
         if ($property->getSlug() !== $slug) {
             return $this->redirectToRoute('property_show', [
                 'id' => $property->getId(),
                 'slug' => $property->getSlug()
             ], 301);
         }
         $contact= new Contact();
         $contact->setProperty($property);
         $form=$this->createForm(ContactType::class,$contact);
         $form->handleRequest($request);
         if (  $form->isSubmitted() && $form->isValid()){
             $notification->notify($contact);
         $this->addFlash('success','votre a été bien envoyer');
             return $this->redirectToRoute('property_show', [
                 'id' => $property->getId(),
                 'slug' => $property->getSlug()
             ]);
         }

         return $this->render('property/show.html.twig', [
             'property'=>$property,
             'menu_courant' => 'properties',
             'form'=> $form->createView()
         ]);     }


}

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Acheter Article{% endblock %}

{% block body %}

    <div class="jumbotron">
        <div class="container">
            {{ form_start(form) }}
            <div class="form-row align-items-end">
                <div class="col">
                    {{ form_row(form.minSurface) }}
                </div>
                <div class="col">
                    {{ form_row(form.maxPrice  ) }}
                </div>
                <div class="col">
                    {{ form_row(form.options  ) }}
                </div>
                <div class="col">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">
                            Rechercher
                        </button>
                    </div>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
    <div class="container mt-4">
        <h1>Nos biens</h1>
        <div class="row">
            {% for property in properties %}
                <div class="col-md-4">
                    {{ include ('property/property.html.twig') }}
                </div>
            {% endfor %}
        </div>
        <div class="navigation">
            {{ knp_pagination_render(properties) }}
        </div>
    </div>
{% endblock %}

templates/property/property.html.twig
<div class="card mb-4">
    {% if property.filename %}
        <img src="{{ vich_uploader_asset(property,'imageFile') | imagine_filter('thumb') }}" class="card-img-top img-fluid " alt="" style="width: 100%; height:auto;">
    {% else %}
        <img src="{{ '/images/properties/empty.jpg' | imagine_filter('thumb') }}" alt="" class="card-img-top img-fluid">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ path('property_show', {slug: property.slug, id: property.id }) }}">
                {{ property.title }}
            </a>
        </h5>
        <p class="card-text">
            {{ property.surface }} m2 - {{ property.city }} ({{ property.postalCode }})
            <br>
            <span class="text-primary" style="font-size: 2rem; font-weight: bold;">
                {{ property.formatedprix }}
            </span>
        </p>
    </div>
</div>

templates/property/show.html.twig
{% extends 'base.html.twig' %}
{% block title property.title %}

{% block body %}

<div class="jumbotron">
    <div class="container">
        {% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}

        {% if not form.vars.valid %}
            <div class="alert alert-danger">
                Watch oooout !!!
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-8">
                {% if property.filename %}
                    <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('medium') }}" class="card-img-top img-fluid " alt="" style="width: 1000%; height:auto;">
                {% else %}
                    <img src="{{ '/images/properties/empty.jpg' | imagine_filter('medium') }}" alt="" class="card-img-top img-fluid">
                {% endif %}
            </div>
            <div class="col-md-4 ">
                <h1> {{property.title }}</h1>
                <h2> {{ property.rooms }} pieces-{{ property.surface }} m<sup>2</sup>  </h2>
                <div class="text-primary" style="font-size:3rem;font-weight: bold">{{ property.formatedprix }} €</div>
                <a href="" class="btn btn-primary"
                   id="contactButton"{% if form.vars.submitted %} style="display: none;"{% endif %}>Contacter
                    l'agence</a>
                <div id="contactForm"
                     class="mt-4"{% if not form.vars.submitted %} {% endif %}>
                    {{ form_start(form) }}
                    <div class="row">
                        <div class="col">{{ form_row(form.firstname) }}</div>
                        <div class="col">{{ form_row(form.lastname) }}</div>
                    </div>
                    <div class="row">
                        <div class="col">{{ form_row(form.phone) }}</div>
                        <div class="col">{{ form_row(form.email) }}</div>
                    </div>
                    {{ form_rest(form) }}
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Envoyer</button>
                    </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
</div>
    <div class="container mt-4 ">
        <p>
            {{ property.description |nl2br }}
        </p>
        <div class="row">
            <div class="col-md-8">
                <h2>Caractéristique</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Surface habitable </td>
                        <td>{{ property.surface }}</td>
                    </tr>
                    <tr>
                        <td>Piéces</td>
                        <td>{{ property.rooms }}</td>
                    </tr>
                    <tr>
                        <td>Chambres</td>
                        <td>{{ property.bedrooms }}</td>
                    </tr>
                    <tr>
                        <td>Etage </td>
                        <td>{{ property.floor }}</td>
                    </tr>
                    <tr>
                        <td>Chuafage </td>
                        <td>{{ property.heatType }}</td>
                    </tr>
                </table>
            </div>
            <div class="col-md-4">
                <h2>Spécifique</h2>
                <ul class="list-group">
                    {% for option in property.options %}
                        <li class="list-group-item">{{ option.name }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>





{% endblock %}